theme: jekyll-theme-hacker

title: "Curso Series Temporales 2021"
description: "PÃ¡gina de entregas del curso Series Temporales 2021 -- Universidad ORT Uruguay -- Master en Big Data e Inteligencia Arrtificial."

show_downloads: "False"
